### ISSUE TITLE
[Bug] Download Speed stuck

### ISSUE THREAD

**Issue by s0ldi3r4** [iyear/tdl#576]
### Describe the bug

When started the download (and also the forwarding), the download speed is incompatible with the actual internet download speed(I have 1gbps) 
![image](https://github.com/iyear/tdl/assets/151221785/a52f88cd-d9bf-463d-af8f-129af01920f8)
In the example above, it's at 5mbps

### To Reproduce

1. **Run** the command for forward: tdl forward --from tdl-export.json --to CHAT --mode clone --desc
2. **Click on** Wait download start
3. **See error**: Download speed stuck in 4-5mbps

### Expected behavior

I expected the download speed to be compatible with the internet speed

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by 1368129224** [comment]
Are you Telegram Premium?
As far as I know telegram has a speed limit.

**Comment by s0ldi3r4** [comment]
> Are you Telegram Premium? As far as I know telegram has a speed limit.

No :((((

**Comment by phanirithvij** [comment]
I have telegram premium and I too get 4MBps and sometimes rarely 8-10MBps for a few minutes, I think we will have to live with this speed.

**Comment by keerthiteja** [comment]
My Internet speed as per speednet.net is 460mbps with download latency 2. 
I have telegram premium and my download speed with tdl is 5MB/s. Few months back when I tried it was so fast, Now I have no idea why the download speed stuck at 5 MB.

**Comment by iyear** [comment]
I published release [v0.17.3](https://github.com/iyear/tdl/releases/tag/v0.17.3), can you try it?

**Comment by keerthiteja** [comment]
@iyear Hi, I updated to the latest version but still see the same 5mb download speed.

![tdl](https://github.com/iyear/tdl/assets/4180100/9efb38e0-93a2-409b-a24c-1e3c8075e0ab)
![speed](https://github.com/iyear/tdl/assets/4180100/b1f3d912-4689-4e5f-84ee-ee3109e4b420)
![tg](https://github.com/iyear/tdl/assets/4180100/38459e94-0c47-4388-93cf-7055f01f9925)

**Comment by iyear** [comment]
@keerthiteja Try flag: `-t 16 -l 5(or higher)`

**Comment by keerthiteja** [comment]
@iyear 1 MB/s increased with -l 12 
![tdl1](https://github.com/iyear/tdl/assets/4180100/dc0d952b-629e-459b-8d8f-bfa609d6dc83)

**Comment by iyear** [comment]
@keerthiteja It seems like the rate limiting is coming from the server side, which is a black box for us and very difficult to debug. :(

**Comment by h1n4mx0** [comment]
> @keerthiteja It seems like the rate limiting is coming from the server side, which is a black box for us and very difficult to debug. :(

Have you solved this problem yet?
